# Codecov Configuration for Just Spent
# This configuration adjusts coverage targets to be realistic for UI-heavy mobile apps

coverage:
  # Overall project coverage status
  status:
    project:
      default:
        # Overall project target - less strict since we have a lot of UI code
        target: 50%
        threshold: 5%
        # Only fail if coverage drops significantly
        if_ci_failed: error

    patch:
      default:
        # Patch (diff) coverage target - lowered because UI code is hard to unit test
        # UI components (Compose/SwiftUI) are primarily tested via UI tests which
        # don't contribute to JaCoCo/Xcode coverage reports
        target: 30%
        threshold: 10%
        # Don't block PRs on patch coverage for UI code
        if_ci_failed: error

# Ignore UI components from strict coverage requirements
# These are tested via UI tests (androidTest/JustSpentUITests) which don't
# contribute to the JaCoCo coverage reports uploaded to Codecov
ignore:
  # Android UI components (Jetpack Compose)
  - "android/app/src/main/java/**/ui/components/**"
  - "android/app/src/main/java/**/ui/expenses/**"
  - "android/app/src/main/java/**/ui/onboarding/**"
  - "android/app/src/main/java/**/ui/main/**"

  # iOS Views (SwiftUI)
  - "ios/JustSpent/JustSpent/Views/**"

  # Generated files
  - "**/*Generated*"
  - "**/BuildConfig.*"
  - "**/R.kt"
  - "**/R$*.kt"

# Comment configuration
comment:
  layout: "header, diff, flags, components"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Flag definitions for different test types
flags:
  android-unit:
    paths:
      - android/
    carryforward: true

  ios-unit:
    paths:
      - ios/
    carryforward: true

# Component management for clearer reporting
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
      - type: patch
        target: auto

  individual_components:
    # Core business logic - stricter requirements
    - component_id: android-utils
      name: Android Utilities
      paths:
        - android/app/src/main/java/**/utils/**
        - android/app/src/main/java/**/data/**

    - component_id: ios-utils
      name: iOS Utilities
      paths:
        - ios/JustSpent/JustSpent/Utils/**
        - ios/JustSpent/JustSpent/Models/**

    # UI components - relaxed requirements (tested via UI tests)
    - component_id: android-ui
      name: Android UI
      paths:
        - android/app/src/main/java/**/ui/**

    - component_id: ios-ui
      name: iOS UI
      paths:
        - ios/JustSpent/JustSpent/Views/**
