package com.justspent.expense

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner
import dagger.hilt.android.testing.HiltTestApplication

/**
 * Custom test runner for Hilt-based instrumented tests
 *
 * This replaces JustSpentApplication with the Hilt-generated test application during tests.
 * The generated application (JustSpentTestApplication_Application) is based on
 * JustSpentTestApplicationBase and includes Hilt functionality plus app-specific
 * initialization (like Currency system).
 *
 * Note: Hilt generates a class with suffix "_Application" based on the @CustomTestApplication
 * annotation. If that's not available, falls back to HiltTestApplication.
 */
class HiltTestRunner : AndroidJUnitRunner() {
    override fun newApplication(
        cl: ClassLoader?,
        className: String?,
        context: Context?
    ): Application {
        // Try to use the custom test application generated by @CustomTestApplication
        // Falls back to HiltTestApplication if generation fails
        return try {
            super.newApplication(cl, "com.justspent.expense.JustSpentTestApplication_Application", context)
        } catch (e: Exception) {
            super.newApplication(cl, HiltTestApplication::class.java.name, context)
        }
    }
}

