source "https://rubygems.org"

# Fastlane and dependencies
gem "fastlane", "~> 2.217"

# Plugins
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
